spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baselineOnMigrate: true
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: 238051pwr@gmail.com
    password: Haslo_11
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            requiered: true
        transport:
          protocol: smtp

file:
  logo: ${IMG_PATH:D:\pracadyplomowa\praca-front\src\assets}
  horse: ${IMG_PATH:D:\pracadyplomowa\praca-front\src\assets}
url:
  server: ${URL_SERVER:http://localhost:4200}